version: "3.8"

services:
  e-commerce-auth-mysql:
    image: mysql:8.0.31
    ports:
      - ${MYSQL_BINDING_PORT}:${MYSQL_PORT}
    volumes:
      - ${MYSQL_CUSTOM_CONFIG_PATH}:/etc/mysql/conf.d
      - ${MYSQL_DATA_PATH}:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TZ}
    env_file:
      - env/.env