server:
  shutdown: graceful
  port: 8200

spring:
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

  profiles:
    active: local
    group:
      local:
#        - local-h2
        - local-mysql

      dev:

      prod:

    include:

logging:
  level:
    com.example.admin.auth.service: debug
